// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDockerHost() {
  return window['go']['main']['App']['GetDockerHost']();
}

export function GetDockerStatus() {
  return window['go']['main']['App']['GetDockerStatus']();
}

export function ListContainers() {
  return window['go']['main']['App']['ListContainers']();
}

export function ListImages() {
  return window['go']['main']['App']['ListImages']();
}

export function Reconnect() {
  return window['go']['main']['App']['Reconnect']();
}

export function ResizeExec(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeExec'](arg1, arg2, arg3);
}

export function SendExecInput(arg1, arg2) {
  return window['go']['main']['App']['SendExecInput'](arg1, arg2);
}

export function StartComposeGroup(arg1) {
  return window['go']['main']['App']['StartComposeGroup'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StartExec(arg1, arg2) {
  return window['go']['main']['App']['StartExec'](arg1, arg2);
}

export function StopComposeGroup(arg1) {
  return window['go']['main']['App']['StopComposeGroup'](arg1);
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function StopExec(arg1) {
  return window['go']['main']['App']['StopExec'](arg1);
}

export function StopLogs(arg1) {
  return window['go']['main']['App']['StopLogs'](arg1);
}

export function StreamLogs(arg1, arg2) {
  return window['go']['main']['App']['StreamLogs'](arg1, arg2);
}
