// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDockerHost():Promise<string>;

export function GetDockerStatus():Promise<Record<string, any>>;

export function ListContainers():Promise<Array<main.ContainerInfo>>;

export function ListImages():Promise<Array<main.ImageInfo>>;

export function Reconnect():Promise<string>;

export function ResizeExec(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SendExecInput(arg1:string,arg2:string):Promise<void>;

export function StartComposeGroup(arg1:string):Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StartExec(arg1:string,arg2:string):Promise<string>;

export function StopComposeGroup(arg1:string):Promise<void>;

export function StopContainer(arg1:string):Promise<void>;

export function StopExec(arg1:string):Promise<void>;

export function StopLogs(arg1:string):Promise<void>;

export function StreamLogs(arg1:string,arg2:number):Promise<void>;
